```{r}
#load dataset library
library(fivethirtyeight)
```

```{r}
#call dataset and assign variable name
drivers <- bad_drivers
```
```{r}
summarise(drivers)
```

```{r}
#install and/or call tidyverse package
install.packages("tidyverse")
library(tidyverse)
```

```{r}
#subset dataset to be Colorado and Colorado by calling dplyr and slicing the dataset
library(dplyr)
drivers_subset <- drivers %>%
slice(c(6,48))
print(drivers_subset)

```
```{r}
#create bar graph 
ggplot(drivers_subset, aes(x= state, y= num_drivers, fill = state)) +
  geom_bar (stat = "identity")+
   labs(
    x = "State",
    y= "Drivers in fatal crashs",
    title = "Fatal Accidents Per Billion Miles: Colorado vs. Washington")
```
```{r}
ggplot(drivers_subset, aes(x= state, y= perc_speeding, fill = state)) +
  geom_bar (stat = "identity")+
   labs(
    x = "State",
    y= "Fatal crashes from speeding",
    title = "Fatal Crashes with Reported Speeding: Colorado vs. Washington")
```

``` {r}
ggplot(drivers_subset, aes(x=state, y=perc_alcohol, fill = state)) +
  geom_bar (stat = "identity")+
  labs(
    x = "State",
    y= "Fatal crashes due to alcohol",
    title = "Fatal Crashes with Alcohol Involved: Colorado vs. Washington")
```
